apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: consumer
  name: consumer
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
  selector:
    matchLabels:
      service: consumer
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: consumer
    spec:
      containers:
      - image: 534970752686.dkr.ecr.us-east-1.amazonaws.com/indexas-backend:0.0.4
        command: ["yarn"]
        args: ["consumer"]
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
        name: consumer    
      restartPolicy: Always
