apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - name: ipfs-daemon
          image: ceramicnetwork/go-ipfs-daemon:latest
          envFrom:
          - configMapRef:
              name: ipfs-env
          ports:
            - name: api
              containerPort: 5001
            - name: healthcheck
              containerPort: 8011
          startupProbe:
            httpGet:
              port: healthcheck
              path: /
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: healthcheck
              path: /
            failureThreshold: 1
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  type: ClusterIP
  selector:
    app: ipfs
  ports:
    - name: api
      port: 5001
      targetPort: api
