apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconnect
  labels:
    app: kafkaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconnect
  template:
    metadata:
      labels:
        app: kafkaconnect
    spec:
      containers:
        - name: kafkaconnect-container
          image: 534970752686.dkr.ecr.us-east-1.amazonaws.com/debezium-connect:2.1
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka.composedb:9092
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: ENABLE_DEBEZIUM_SCRIPTING
              value: "true"
            - name: KAFKA_OPTS
              value: "-Dfile.encoding=UTF-8"
          ports:
          - containerPort: 8083
---

apiVersion: v1
kind: Service
metadata:
  name: kafkaconnect
  labels:
    app: kafkaconnect
spec:
  ports:
    - name: kafkaconnect
      protocol: TCP
      port: 8083
  selector:
      app: kafkaconnect