primary:
  extendedConfiguration: |
    wal_level= logical
    max_wal_senders= 10
    max_replication_slots= 10
persistence:
  enabled: true
  size: 40Gi
auth:
  existingSecret: postgresql-secret
  passwordKey: postgresql-password
